config/routes.rb
Rails.application.routes.draw do
  namespace :communication do
    resources :communications, only: [:index,:new ,:create]
    resources :communication_details, only: [:new,:create]
     #conversation row click
     get "conversation_forum/:id", to: "communications#conversation_forum", as: "conversation_forum" 
  end
  get 'rails/g'
  get 'rails/controller'
  #For admin sing_in
  get 'bl-admin', as: "bl-admin", to:"admin/dashboard#admin"
   
   # commons Controller
   scope ':scop_name' do
    get "user_setting" ,to: "commons#user_setting"
    get "genuine_password" ,to: "commons#genuine_password"
   end
   patch "genuine_password_change/:confirmation_token" ,to: "commons#genuine_password_change" ,as: 'genuine_password_change'
   patch "user_setting_update" ,to: "commons#user_setting_update"
   get "get_region_name_by_prefecturename/:name", to: "commons#get_region_name_by_prefecturename"

  namespace :welcome do
    get 'welcomes/index', as: 'index'
    get 'student', as: 'student', to: "welcomes#student_index"
    get 'company', as: 'company', to: "welcomes#company_index"
    get 'contact', as: "contact", to:"welcomes#contact_index"
    get 'privacy', as: "privacy", to:"welcomes#privacy_index"
    get 'term_condition', as: "term_condition", to:"welcomes#term_condition_index"
    get 'registration_complete', as: "registration_complete", to:"welcomes#registration_complete"
    post 'contact_create', as: "contact_create", to:"welcomes#contact_create"
    get 'student_login', as: "student_login", to:"welcomes#student_login"
    get 'student_register', as: "student_register", to:"welcomes#student_register"
    get 'company_login', as: "company_login", to:"welcomes#company_login"
    get 'company_register', as: "company_register", to:"welcomes#company_register"
  end

  namespace :company do
    resources :companies, only: [:index,:edit,:update, :create,:show]
    resources :vacancies , only: [:index,:new,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    resources :events
    #Student Search and Detail
    get "students_search" , to: "search#student_search"
    get "student_details/:id", to: "search#student_details", as: "student_details"
    get "index", to: "search#index"
    get "favourite_student/:id", to: "search#favourite_student", as: "favourite_student" 
    get "getLocationDetails", to: "search#getLocationDetails"
    get "favourite_student_index", to: "companies#favourite_student_index"
    get "join_event_student_list/:id", to: "companies#join_event_student_list", as: "join_event_student_list"
    #set mail setting
    get "mail_settings/:mail_setting", to: "companies#mail_settings"
  end

  namespace :student do
    resources :students, only: [:index,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    get "student_smart_brain_diagnosis" , to: "assessments#student_smart_brain_diagnosis"
    get "student_potential_desire_type_diagnosis" , to: "assessments#student_potential_desire_type_diagnosis"
    get "student_behavioral_trait_type" , to: "assessments#student_behavioral_trait_type"
    #company Search and Detail
    get "companies_search" , to: "search#company_search"
    get "companies_detail/:id" , to: "search#company_detail"
    get "favourite_company/:id", to: "search#favourite_company"
    #Seach Vacancy and Detail
    get "vacancy_search" , to: "search#vacancy_search"
    get "favourite_vacancy/:id", to: "search#favourite_vacancy"
    #Search Event
    get "search_event", to: "search#search_event"
    get "search_event_detail/:id" , to: "search#search_event_detail", as: "event_details"
    get "favourite_event/:id", to: "search#favourite_event"
    get "join_event/:id", to: "search#join_event"

    get "prefecture_name/:id", to: "students#prefecture_name"
    get "favourite_company_index", to: "students#favourite_company_index"
    get "favourite_vacancy_index", to: "students#favourite_vacancy_index"
    get "favourite_event_index", to: "students#favourite_event_index"
    get "join_event_index", to: "students#join_event_index" 
  end

  devise_for :users, path: "users", controllers: { sessions: "users/sessions",passwords: "users/passwords", registrations: "users/registrations", confirmations: 'users/confirmations' }
  devise_scope :user do
    get "/logout", to: "users/sessions#destroy", as: :logout
    get "users", to: "welcome/welcomes#index"
  end

  devise_for :admins, path: "admins", controllers: { sessions: "admin/admins/sessions",passwords: "admin/admins/passwords"}
  devise_scope :admins do
    get "sign_in", to: "admin/admins/sessions#new"
    get "logout", to: "admin/admins/sessions#destroy"
  end

  namespace :admin do
    get 'dashboard/index'
    get 'password_change' , to: "commons#admin_password_change"
    post 'password_update' , to: "commons#password_update"
    get 'admin_student_setting', to: "student_manage/student#admin_student_setting"
    get 'admin_company_setting', to: "company_manage/company#admin_company_setting"
    get 'set_permission/:type_id/:user_id', to: "commons#set_permission"
    resources :backup_db

    namespace :student_manage do
      # Admin Student
      get 'student_search', to: 'student#student_search'
      get 'student_details', to: 'student#student_details'
      get 'student_edit', to: 'student#student_edit'
      get 'student_delete', to: 'student#student_delete'
      post 'student_update/:id', to: 'student#student_update'
      get 'admin_favourite_student', to: 'student#admin_favourite_student' 
    end
    namespace :company_manage do
      # Admin Company
      get 'company_search', to: 'company#company_search'
      get 'company_details', to: 'company#company_details'
      get 'company_edit', to: 'company#company_edit'
      post 'company_update/:id', to: 'company#company_update', as: "company_update"
      get 'company_delete', to: 'company#company_delete'
      get 'favourite_company', to: 'company#favourite_company'

      # Admin Event 
      get 'event_search', to: 'events#event_search'
      get 'event_details', to: 'events#event_details'
      get 'event_edit', to: 'events#event_edit'
      post 'event_update/:id', to: 'events#event_update', as: "event_update"
      get 'event_delete', to: 'events#event_delete'

      # Admin Vacancy
      get 'vacancy_search', to: 'vacancies#vacancy_search'
      get 'vacancy_details', to: 'vacancies#vacancy_details'
      get 'vacancy_edit', to: 'vacancies#vacancy_edit'
      post 'vacancy_update/:id', to: 'vacancies#vacancy_update', as: "vacancy_update"
      get 'vacancy_delete', to: 'vacancies#vacancy_delete'
    end
  end
 
  root to: 'welcome/welcomes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?
    if resource.errors.empty?
      set_flash_message!(:notice, :confirmed)
      respond_with_navigational(resource){ redirect_to genuine_password_path(confirmation_token: resource.confirmation_token,scop_name: resource.user_type == 2 ? "student" : "company") }
    else
      # set_flash_message!(:notice, "#{resource.errors.full_messages}")
      Users::SessionsController.set_userType(resource.user_type.to_s)
      if resource.encrypted_password.blank?
        respond_with_navigational(resource.errors, status: :unprocessable_entity){redirect_to(genuine_password_path(confirmation_token: resource.confirmation_token,scop_name: resource.user_type == 2 ? "student" : "company")) } 
      else
        respond_with_navigational(resource.errors, status: :unprocessable_entity){redirect_to(user_session_path) }
      end
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      signed_in_root_path(resource)
    else
      Users::SessionsController.set_userType(resource.user_type.to_s)
      new_user_session_path
    end
    # super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :set_user_type, only: [:new ,:create,:edit,:update]
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
      new_session_path(resource,user_type: resource.user_type)
    # super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    # super(resource_name)
    new_session_path(resource_name,user_type: resource.user_type)
  end

  def set_user_type
    @user_type = params[:user_type]
  end 
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :set_user_type, only: [:new, :create]
  # before_action :configure_account_update_params, only: [:update]


  #set data for global user_type
  @@type = 0

  #this function is called from other Class
  def self.set_userType(data)
    @@type = data
  end

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super do 
      if resource.save
        if resource.user_type == 2
          student = Student::Student.new
          student.user_id = resource.id
          student.first_name = params[:user][:first_name]
          student.last_name = params[:user][:last_name]
          student.save(validate: false)
        else
          company = Company::Company.new
          company.user_id = resource.id
          company.company_name = params[:user][:company_name]
          company.save(validate: false)
        end
      else
        @user_type = resource.user_type
      end
      
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password, :user_name, :user_type, :last_name, :company_name, :first_name,:company_email,:terms_and_conditions, :privacy_policy])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    welcome_registration_complete_path(user_type: resource.user_type)
    # super(resource)
  end
  def set_user_type
    @user_type = @@type
  end 
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_path, only: :destroy
  before_action :configure_sign_in_params, only: [:create]
  before_action :set_user_type, only: [:new ,:create]

  #set data for global user_type
  @@type = 0
  @@active_flag = false

  #this function is called from other Class
  def self.set_userType(data)
    @@type = data
  end

  def self.set_activeFlag(flag)
    @@active_flag = flag
  end

  def self.get_activeFlag
    @@active_flag
  end

  #GET /resource/sign_in
  # def new
  #   super
  # end

  ##POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super do 
      flash.clear
    end
  end

  # protected
  def set_user_type
    @user_type = @@type
  end 
  
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login,:password,:user_type])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/user_setting/genuine_password.html.erb
<div class="container p-3 p-sm-5">
  <div class="row justify-content-center my-5 p-2">
    <div class="col-12 col-xl-8">
      <div class="card login-card-shadow bg-white p-3 p-sm-5">
        <div class="text-group-left mb-4">          
            <h3 class="text-center"><%= t('genuine_password.title') %></h3>
            <% if @setting_user.user_type.eql?2 %>   
              <hr class="std-grandient-hr">   
            <% else %>     
              <hr class="com-grandient-hr">   
            <% end %>            
        </div>
        <%= form_with(model: @setting_user, url: genuine_password_change_path(@setting_user.confirmation_token), method: "patch") do |f| %>
        <%= render "users/shared/flash", resource: @setting_user %>
            <div class="mb-3">
              <div class="d-flex">
                  <%= f.label :password, class: "form-label" %>
                  <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div>
              <%= f.password_field :password, class: "form-control shadow-none errors" %>
              <p class="ms-invalid-feedback"><%= @setting_user.errors.full_messages_for(:password)[0] %></p>
            </div>  

            <div class="mb-4">
              <div class="d-flex">
                  <%= f.label :password_confirmation, class: "form-label" %>
                  <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div>
              <%= f.password_field :password_confirmation, class: "form-control shadow-none errors" %>
              <p class="ms-invalid-feedback"><%= @setting_user.errors.full_messages_for(:password_confirmation)[0] %></p>
            </div>

            <% if @setting_user.user_type.eql?2 %> 
            <div class="d-flex">
              <%= f.submit t('genuine_password.save_password'), class: "custom-btn text-white w-50 std-bg-color p-1 col-12 col-sm-12 " %>  
            </div>             
          <% else %>    
            <div class="d-flex justify-content-end">           
              <%= f.submit t('genuine_password.save_password'), class: "custom-btn text-white w-50 com-bg-color p-1 col-12 col-sm-12" %>  
            </div> 
          <% end %>  
      <% end %>
      </div>
   </div>
  </div> 
</div>

app/views/users/user_setting/setting.html.erb
<div class="container setting">
    <div class="mt-5 pt-5">
        <%# New Form Design %>
        <div class="row justify-content-center">
            <div class="col-xs-12 col-lg-10 ms-form-group" id="content">
                <% flash.each do |key, value| %>
                    <% if value != nil %>
                        <% if key == 'email_change' %>
                            <div class="container">
                                <div class="alert alert-success" role="alert">
                                <%= value %>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
                <%= form_with(model: @setting_user , url: user_setting_update_url , method: "patch") do |f| %>
                    <div class="shadow mb-5 bg-white d-flex flex-column justify-content-between rounded">
                        <div class="text-group-left">
                            <div class="px-5 pt-5 w-100">
                                <h3 class="text-center"><%= t ('password_setting.title.change_login_setting') %></h3>
                                <% if @setting_user.user_type.eql?2 %> 
                                    <hr class="std-grandient-hr">   
                                <% else %>     
                                    <hr class="com-grandient-hr">   
                                <% end %> 
                            </div>
                        </div>
                        <div class="px-lg-5 pt-lg-5 px-md-3 pt-md-3 px-3 pt-3">
                            <%# Current Password %>
                            <div class="row">
                                <div class="col-xs-12 col-lg-12">
                                    <div class="d-flex">
                                        <%= f.label :current_password , class: "form-label"%>
                                        <label class="ml-auto required-label"><%= t('common.require') %> </label>
                                    </div>
                                    <%= f.password_field :current_password, class: "form-control shadow-none errors",placeholder: t("password_setting.current_password"),:id=>"password" %>
                                    <p class ="ms-invalid-feedback mt-1"><%= flash[:password_notice] %></p>
                                </div>                       
                            </div>

                            <%# Show/Hide username and password %>
                            <div class="row mt-1">
                                <%# Change Username %>
                                <% if @setting_user.user_type.eql?2 %>
                                    <div class="simple-chkbox std-chk col-xs-12 col-md-6">
                                        <%= f.check_box :chk_edit_email, :as => :boolean, checked: @setting_user.chk_edit_email == '1' ? true : false, class: 'chk_email' %>
                                        <label for="user_chk_edit_email"  ><%=  t('password_setting.change_email')%></label>                               
                                    </div>
                                    <%# Change password %>
                                    <div class="simple-chkbox std-chk col-xs-12 col-md-6">
                                        <%= f.check_box :chk_pass_edit, :as => :boolean, checked: @setting_user.chk_pass_edit == '1' ? true : false, class: 'chk_pass'%>
                                        <label for="user_chk_pass_edit"><%=  t('password_setting.change_password')%></label>                               
                                    </div>
                                <% else %>
                                    <div class="simple-chkbox com-chk col-xs-12 col-md-6">
                                        <%= f.check_box :chk_edit_username, :as => :boolean, checked: @setting_user.chk_edit_username == '1' ? true : false, class: 'chk_email' %>
                                        <label for= "user_chk_edit_username"><%=  t('password_setting.change_username')%></label>                               
                                    </div>
                                    <%# Change password %>
                                    <div class="simple-chkbox com-chk col-xs-12 col-md-6">
                                        <%= f.check_box :chk_pass_edit, :as => :boolean, checked: @setting_user.chk_pass_edit == '1' ? true : false, class: 'chk_pass'%>
                                        <label for="user_chk_pass_edit"><%=  t('password_setting.change_password')%></label>                               
                                    </div>
                                <% end %>
                                
                            </div>

                            <%# Current username and password %>
                            <div class="row mt-1">
                            <% if @setting_user.user_type.eql?2 %>
                            <%# Change Username %>
                                <div class="col-xs-12 col-md-6">
                                    <div class="edit_username show">
                                        <div class="d-flex">
                                            <%= f.label :email %>
                                            <label class="ml-auto required-label"><%= t('common.require') %> </label>
                                        </div>
                                        <%= f.email_field :email, :class=> "form-control shadow-none errors", disabled: false %>
                                        <p class="ms-invalid-feedback mt-1"><%= @setting_user.errors.full_messages_for(:email)[0] %></p>
                                    </div>
                                </div>
                            <% else %>
                            <%# Change Username %>
                                <div class="col-xs-12 col-md-6">
                                    <div class="edit_username show">
                                        <div class="d-flex">
                                            <%= f.label :user_name %>
                                            <label class="ml-auto required-label"><%= t('common.require') %> </label>
                                        </div>

                                        <%= f.text_field :user_name, pattern: "[a-zA-Z0-9-_.]{1,20}",id: "username", :class=> "form-control shadow-none errors", disabled: false %>
                                        <p class="ms-invalid-feedback mt-1"><%= @setting_user.errors.full_messages_for(:user_name)[0] %></p>
                                    </div>
                                </div>
                            <% end %>
                                 <%# Change password %>
                                <div class="col-xs-12 col-md-6 ">
                                    <div class="edit_password show">                            
                                        <div class="d-flex">
                                            <label class="form-label"><%= t('password_setting.new_password') %> </label>
                                            <label class="ml-auto required-label"><%= t('common.require') %> </label>
                                        </div>
                                        <%= f.password_field :password, :class=> "form-control shadow-none errors", placeholder: t("password_setting.new_password"), disabled: false %>
                                        <p class="ms-invalid-feedback mt-1"><%= flash[:password] %></p>

                                        <div class="d-flex">
                                            <%= f.label :password_confirmation, class: "form-label" %>
                                            <label class="ml-auto required-label"><%= t('common.require') %> </label>
                                        </div>
                                        <%= f.password_field :password_confirmation, :class=> "form-control shadow-none errors", placeholder: t("password_setting.password_confirmation"),disabled: false %>
                                        <p class="ms-invalid-feedback mt-1"><%= flash[:password_confirmation] %></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <%# Action Area %>
                        <div class="d-block d-lg-flex justify-content-lg-end pb-5 px-lg-5 pb-lg-5 p-md-3 px-sm-3 pb-sm-3 p-3">                            
                            <% if @setting_user.user_type.eql?2 %>
                                <%= f.submit t("btn.submit") , :class => "float-left col-5 col-md-5 col-lg-3 custom-btn px-4 py-2 py-md-3 py-lg-2 std-bg-color text-white text-center mr-lg-3", :id=>"password-button"%>
                                <%= link_to  t("btn.cancel") ,student_student_path(@setting_user), :class => "float-right col-5 col-md-5 col-lg-3 std-bg-color custom-btn px-0 px-md-4 py-2 py-md-3 py-lg-2 text-white text-center text-decoration-none" %>
                            <% else %>
                                <%= f.submit t("btn.submit") , :class => "float-left col-5 col-md-5 col-lg-3 custom-btn px-4 py-2 py-md-3 py-lg-2 com-bg-color text-white text-center mr-lg-3", :id=>"password-button"%>
                                <%= link_to  t("btn.cancel") ,company_company_path(@setting_user), :class => "float-right col-5 col-md-5 col-lg-3 com-bg-color custom-btn px-0 px-md-4 py-2 py-md-3 py-lg-2 text-white text-center text-decoration-none" %>
                            <% end %>
                        </div>                          
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>
<%= javascript_pack_tag "company/company.js" %>