config/routes.rb
Rails.application.routes.draw do
  namespace :communication do
    resources :communications, only: [:index,:new ,:create]
    resources :communication_details, only: [:new,:create]
     #conversation row click
     get "conversation_forum/:id", to: "communications#conversation_forum", as: "conversation_forum" 
  end
  get 'rails/g'
  get 'rails/controller'
  #For admin sing_in
  get 'bl-admin', as: "bl-admin", to:"admin/dashboard#admin"
   
   # commons Controller
   scope ':scop_name' do
    get "user_setting" ,to: "commons#user_setting"
    get "genuine_password" ,to: "commons#genuine_password"
   end
   patch "genuine_password_change/:confirmation_token" ,to: "commons#genuine_password_change" ,as: 'genuine_password_change'
   patch "user_setting_update" ,to: "commons#user_setting_update"
   get "get_region_name_by_prefecturename/:name", to: "commons#get_region_name_by_prefecturename"

  namespace :welcome do
    get 'welcomes/index', as: 'index'
    get 'student', as: 'student', to: "welcomes#student_index"
    get 'company', as: 'company', to: "welcomes#company_index"
    get 'contact', as: "contact", to:"welcomes#contact_index"
    get 'privacy', as: "privacy", to:"welcomes#privacy_index"
    get 'term_condition', as: "term_condition", to:"welcomes#term_condition_index"
    get 'registration_complete', as: "registration_complete", to:"welcomes#registration_complete"
    post 'contact_create', as: "contact_create", to:"welcomes#contact_create"
    get 'student_login', as: "student_login", to:"welcomes#student_login"
    get 'student_register', as: "student_register", to:"welcomes#student_register"
    get 'company_login', as: "company_login", to:"welcomes#company_login"
    get 'company_register', as: "company_register", to:"welcomes#company_register"
  end

  namespace :company do
    resources :companies, only: [:index,:edit,:update, :create,:show]
    resources :vacancies , only: [:index,:new,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    resources :events
    #Student Search and Detail
    get "students_search" , to: "search#student_search"
    get "student_details/:id", to: "search#student_details", as: "student_details"
    get "index", to: "search#index"
    get "favourite_student/:id", to: "search#favourite_student", as: "favourite_student" 
    get "getLocationDetails", to: "search#getLocationDetails"
    get "favourite_student_index", to: "companies#favourite_student_index"
    get "join_event_student_list/:id", to: "companies#join_event_student_list", as: "join_event_student_list"
    #set mail setting
    get "mail_settings/:mail_setting", to: "companies#mail_settings"
  end

  namespace :student do
    resources :students, only: [:index,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    get "student_smart_brain_diagnosis" , to: "assessments#student_smart_brain_diagnosis"
    get "student_potential_desire_type_diagnosis" , to: "assessments#student_potential_desire_type_diagnosis"
    get "student_behavioral_trait_type" , to: "assessments#student_behavioral_trait_type"
    #company Search and Detail
    get "companies_search" , to: "search#company_search"
    get "companies_detail/:id" , to: "search#company_detail"
    get "favourite_company/:id", to: "search#favourite_company"
    #Seach Vacancy and Detail
    get "vacancy_search" , to: "search#vacancy_search"
    get "favourite_vacancy/:id", to: "search#favourite_vacancy"
    #Search Event
    get "search_event", to: "search#search_event"
    get "search_event_detail/:id" , to: "search#search_event_detail", as: "event_details"
    get "favourite_event/:id", to: "search#favourite_event"
    get "join_event/:id", to: "search#join_event"

    get "prefecture_name/:id", to: "students#prefecture_name"
    get "favourite_company_index", to: "students#favourite_company_index"
    get "favourite_vacancy_index", to: "students#favourite_vacancy_index"
    get "favourite_event_index", to: "students#favourite_event_index"
    get "join_event_index", to: "students#join_event_index" 
  end

  devise_for :users, path: "users", controllers: { sessions: "users/sessions",passwords: "users/passwords", registrations: "users/registrations", confirmations: 'users/confirmations' }
  devise_scope :user do
    get "/logout", to: "users/sessions#destroy", as: :logout
    get "users", to: "welcome/welcomes#index"
  end

  devise_for :admins, path: "admins", controllers: { sessions: "admin/admins/sessions",passwords: "admin/admins/passwords"}
  devise_scope :admins do
    get "sign_in", to: "admin/admins/sessions#new"
    get "logout", to: "admin/admins/sessions#destroy"
  end

  namespace :admin do
    get 'dashboard/index'
    get 'password_change' , to: "commons#admin_password_change"
    post 'password_update' , to: "commons#password_update"
    get 'admin_student_setting', to: "student_manage/student#admin_student_setting"
    get 'admin_company_setting', to: "company_manage/company#admin_company_setting"
    get 'set_permission/:type_id/:user_id', to: "commons#set_permission"
    resources :backup_db

    namespace :student_manage do
      # Admin Student
      get 'student_search', to: 'student#student_search'
      get 'student_details', to: 'student#student_details'
      get 'student_edit', to: 'student#student_edit'
      get 'student_delete', to: 'student#student_delete'
      post 'student_update/:id', to: 'student#student_update'
      get 'admin_favourite_student', to: 'student#admin_favourite_student' 
    end
    namespace :company_manage do
      # Admin Company
      get 'company_search', to: 'company#company_search'
      get 'company_details', to: 'company#company_details'
      get 'company_edit', to: 'company#company_edit'
      post 'company_update/:id', to: 'company#company_update', as: "company_update"
      get 'company_delete', to: 'company#company_delete'
      get 'favourite_company', to: 'company#favourite_company'

      # Admin Event 
      get 'event_search', to: 'events#event_search'
      get 'event_details', to: 'events#event_details'
      get 'event_edit', to: 'events#event_edit'
      post 'event_update/:id', to: 'events#event_update', as: "event_update"
      get 'event_delete', to: 'events#event_delete'

      # Admin Vacancy
      get 'vacancy_search', to: 'vacancies#vacancy_search'
      get 'vacancy_details', to: 'vacancies#vacancy_details'
      get 'vacancy_edit', to: 'vacancies#vacancy_edit'
      post 'vacancy_update/:id', to: 'vacancies#vacancy_update', as: "vacancy_update"
      get 'vacancy_delete', to: 'vacancies#vacancy_delete'
    end
  end
 
  root to: 'welcome/welcomes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/company_manage/company_controller.rb
class Admin::CompanyManage::CompanyController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin_company, only: %i[ company_edit company_update ]

  include CommonHelper
  layout 'layouts/template/admin'

  def company_search
    startDate = params[:startDate].blank? ? nil : params[:startDate]
    keyword = params[:keyword].blank? ? nil : params[:keyword].strip
    endDate = params[:endDate].blank? ? nil : params[:endDate]
    @vacancy_status = Company::Vacancy.select(:company_id).distinct.map{|data| data.company_id}
    @event_status = Company::Event.select(:company_id).distinct.map{|data| data.company_id}
    if startDate.blank? && !endDate.blank?
      @result_list = Company::Company.admin_search_by_only_end_date(endDate, keyword)  
    elsif(!startDate.blank? && endDate.blank?)
      @result_list = Company::Company.admin_search_by_only_start_date(startDate, keyword)
    elsif(!startDate.blank? && !endDate.blank?)
      @result_list = Company::Company.admin_search_by_between_two_date(startDate, endDate, keyword) 
    else
      @result_list = Company::Company.admin_company_all_init_list(keyword)
    end 
    @results = Kaminari.paginate_array(@result_list).page(params[:page]).per(12)

    respond_to do |format|
      format.html
      format.xlsx { render xlsx: t('search.excel_file_name'), template: 'admin/excel_template/company_excel_export'}
    end
  end

  def company_details
    @company_details = Company::Company.select('companies.*,m_industries.industry_name').left_outer_joins(:m_industries).find(params[:company_id])
    @company_assessment = Company::Assessment.find_by(company_id: params[:company_id])
  end
  

  def company_edit
  end

  def company_update    
    respond_to do |format|
      if @user_company.update(company_params)
        # To delete upload image
        if params[:company_company][:imageFlag] == "true"
          @user_company.image.purge
        end
        unless params[:company_company][:image_data].eql?"false"
          blob = convert_Base64_imgData(params[:company_company][:image_data])
          @user_company.image.attach(blob)
          params[:company_company][:image_data] = false
        end
        format.html { redirect_to admin_company_manage_company_details_path(company_id: @user_company.id)}
        format.json { render :show, status: :ok, location: @user_company }
      else
        format.html { render :company_edit }
        format.json { render json: @user_company.errors, status: :unprocessable_entity }    
      end
    end
  end

  def company_delete
    admin_com_obj = Company::Company.find(params[:id])
    admin_com_obj.update_columns(delete_flg: true)
    admin_com_obj.events.update_all(delete_flg: true)
    admin_com_obj.company_vacancies.update_all(delete_flg: true)
    admin_com_obj.user.update_columns(delete_flg: true, email: admin_com_obj.user.email + "_" + admin_com_obj.user.id.to_s, user_name: admin_com_obj.user.user_name + "_" + admin_com_obj.user.id.to_s)
    if params[:status] == "1"
      redirect_to admin_company_manage_company_search_path      	 
    else
      redirect_to admin_admin_company_setting_path
    end
  end


  def admin_company_setting
    name = params[:company_name].blank? ? nil : params[:company_name].strip
    keyword = params[:keyword].blank? ? nil : params[:keyword].strip
    @permission_type = Admin::MPermissionType.where(use_company: true)
    @permissions = Admin::Permission.where(user_type: 1)
    if name.nil?  && keyword.nil? 
      @results =User.admin_company_setting_all()
    else
      @results = User.admin_company_search_setting(name, keyword)
    end  
    @results = Kaminari.paginate_array(@results).page(params[:page]).per(12)
  end

  def favourite_company
    @favourite_company_list = Company::Company.new.show_top_3_fav_company()
  end

  private
  def set_admin_company
    @user_company = Company::Company.find(params[:id])
    @user = @user_company.user
  end

  def company_params
    params.require(:company_company).permit(:email, :company_name, :company_name_kana, :postal_code, :user_name,
      :address, :display_address, :phone_no, :m_industry_id,:company_info, :image, :website_url, :postalcode_city, :m_region_id, :region_name, :m_prefecture_id, :prefecture_name ,:company_established, :job_info, :contact, :capital_amount, :employee_count, :sales_amount, :related_company, :representative, :main_bank, :history, :transportation_facilities,:avg_service_year, :avg_overtime_per_month, :avg_paid_leaves,:number_eligible_childcare_leaves_male,:taken_childcare_leaves_male,:childcare_leave_acquisition_rate_male,:number_eligible_childcare_leaves_female,:taken_childcare_leaves_female,:rate_taken_childcare_leaves_female,:basic_idea,:percentage_female_ration,:percentage_training,:mentor_system,:career_consulting_system,:in_house_certification_system,:avg_service_year_string,:capital_amount_string,:sales_amount_string)
  end
end

app/controllers/admin/company_manage/events_controller.rb
class Admin::CompanyManage::EventsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_admin_event, only: %i[ event_edit event_update]
    include CommonHelper
    layout 'layouts/template/admin'
   
      def event_search
        keyword = params[:keyword].blank? ? nil : params[:keyword].strip
        event_category_data = params[:category].blank? ? params[:category] = [] : "category && ARRAY#{params[:category].map(&:to_i)}"
        date_type = params[:date_type]
        startDate = params[:startDate].blank? ? nil : params[:startDate]
        endDate = params[:endDate].blank? ? nil : params[:endDate]
        if startDate.blank? && !endDate.blank?
          @event_list = Company::Event.admin_event_search_by_only_end_date(date_type, endDate, keyword, [event_category_data])
        elsif(!startDate.blank? && endDate.blank?)
          @event_list = Company::Event.admin_event_search_by_start_date(date_type, startDate, keyword, [event_category_data])
        elsif(!startDate.blank? && !endDate.blank?)
          @event_list = Company::Event.admin_event_search_by_between_two_date(date_type, startDate, endDate, keyword, [event_category_data])   
        else
            @event_list = Company::Event.admin_event_search_init_list(keyword, [event_category_data])
        end 
        @results_event = Kaminari.paginate_array(@event_list).page(params[:page]).per(12)
      end

      def event_details
        @company_event = Company::Event.find(params[:eventid])
      end

      def event_edit
      end

      def event_update
        respond_to do |format|
          if @company_event.update(event_params)
            # To delete upload image
            if params[:company_event][:imageFlag] == "true"
              @company_event.event_image.purge
            end
            unless params[:company_event][:image_data].eql?"false"
              blob = convert_Base64_imgData(params[:company_event][:image_data])
              @company_event.event_image.attach(blob)
              params[:company_event][:image_data] = false
            end
            format.html { redirect_to admin_company_manage_event_search_path, notice: "Event was successfully updated." }
            format.json { render :show, status: :ok, location: @company_event }
          else
            format.html { render :event_edit}
            format.json { render json: @company_event.errors, status: :unprocessable_entity }
          end
        end
      end

      def event_delete
        admin_event_obj = Company::Event.find(params[:id])
        admin_event_obj.update_columns(delete_flg: true)
        redirect_to admin_company_manage_event_search_path
      end

      private

      def set_admin_event
        @company_event = Company::Event.find(params[:id])
      end

      def event_params
        params.require(:company_event).permit(:event_image,:event_code, :event_start_date, :event_end_date, :event_name, :venue,
        :post_start_date, :post_end_date, :application_deadline, :event_content, :category=> [])
      end
    
end

app/helpers/admin/company_manage/company_helper.rb
module Admin::CompanyManage::CompanyHelper
end

app/helpers/admin/company_manage/events_helper.rb
module Admin::CompanyManage::EventsHelper
end

app/helpers/admin/company_manage/vacancies_helper.rb
module Admin::CompanyManage::VacanciesHelper
end

app/helpers/company/events_helper.rb
module Company::EventsHelper
    def event_category_options
        Company::Event.event_categories.map{ |k,v| [t("event.category.#{k}"),v] }
    end
end

app/views/admin/company_manage/events/_event_delete.html.erb
<button type="button" class="btn-danger col-sm-12 custom-btn px-4 pb-2 pt-1 text-decoration-none" data-toggle="modal" data-target="#event_delete">
    <%= t('common.profile_delete')%>
</button>
<div class="modal fade pl-0" id="event_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content ">
            <div class="modal-header bg-gradient-primary text-white">
                <h3 class="modal-title" id="exampleModalLongTitle"><%= t('common.modal_confirm_title') %></h3>
                <button type="button" class="close text-white btn-close-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body company_type">
                <section>
                    <div class="text-left py-3">
                        <h5 class="text-dark font-weight-bold pl-1"><%= t('search.admin_delete_msg') %></h5>
                    </div>
                    <div class="mt-3 d-flex justify-content-end">
                        <%= link_to t('btn.confirm_yes'), admin_company_manage_event_delete_path(id: @company_event.id), class: "col-sm-5 col-md-4 col-lg-2 com-bg-color text-white font-weight-bold custom-btn px-3 py-2 text-decoration-none" %>         
                        <button type="button" class="btn-secondary text-white font-weight-bold col-sm-6 col-md-4 col-lg-2 custom-btn px-2 py-2 text-decoration-none ml-3" data-dismiss="modal"><%= t('btn.cancel') %></button>
                    </div>
                </section>
            </div>

        </div>
    </div>
</div>

app/views/admin/company_manage/events/event_details.html.erb
<section class="admin-details px-sm-4 d-flex flex-column align-items-center mt-3 mb-5 pb-5">
    <div class="row col-12 bg-white py-5 shadow event-info-box">
        <div class="col-12 col-sm-6 px-2 mb-3">
            <div class="com-font-color h3"><%= t('event.title.event_information')%></div>
        </div>
        <div class="text-center ml-md-auto mb-3 px-2 mt-2">
            <%= link_to t('btn.edit'), admin_company_manage_event_edit_path(id: @company_event.id), class: "com-bg-color text-white col-sm-5 col-md-4 col-lg-2 custom-btn px-3 py-2 text-decoration-none" %> 
        </div>
        <div class="d-flex d-md-block text-center mr-md-4 mb-3">
            <%= render 'event_delete' %>
        </div>

        <div class="row px-2 px-lg-4">
            <div class="col-12 col-lg-3">
                <%  if @company_event.event_image.attached? %>
                    <%= image_tag (@company_event.event_image), :class=> "w-100" %>
                <% else %>
                    <div class="upload-preview">
                    <%= image_tag "avatar/preview.svg"%>
                    </div>
                <% end %>
            </div>
            <div class="col-12 col-md-12 col-lg-9">
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('event_start_date') %></span>
                        <span class="text-secondary"><%= @company_event.event_start_date %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('event_end_date') %></span>
                        <span class="text-secondary"><%= @company_event.event_end_date %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('event_name') %></span>
                        <span class="text-secondary text-break"><%= @company_event.event_name %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('venue') %></span>
                        <span class="text-secondary text-break"><%= @company_event.venue %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('category') %></span>
                        <span class="text-secondary text-break">
                            <% unless @company_event.category.nil?%>
                                <% @company_event.category.each_with_index do |v,i| %>
                                    <%= t("event.category.#{Company::Event.event_categories.key(i+1)}") %>,
                                <% end %>
                            <% end %>
                        </span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('post_start_date') %></span>
                        <span class="text-secondary"><%= @company_event.post_start_date %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('post_end_date') %></span>
                        <span class="text-secondary"><%= @company_event.post_end_date %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('application_deadline') %></span>
                        <span class="text-secondary"><%= @company_event.application_deadline %></span>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3 col-lg-3 my-3 d-flex flex-column">
                        <span class="h6 com-font-color mb-2"><%= Company::Event.human_attribute_name('event_content') %></span>
                        <span class="text-secondary text-break"><%= @company_event.event_content %></span>
                    </div>
                </div>
            </div>
        </div>      
    </div>
</section>

app/views/admin/company_manage/events/event_search.html.erb
<script type="text/javascript">
  var BASE_URL = '<%= root_url %>';
</script>
<%= form_for('',url: admin_company_manage_event_search_path, method: :get) do |form| %>
    <div class="px-sm-4 admin-event-search">
        <div class="col-12 mt-3 mb-4 mb-lg-5 ">
            <div class="row d-lg-flex justify-content-start shadow bg-white py-4 py-lg-3 px-2 px-lg-4">           
                <div class="col-12 col-md-4 col-lg-4 mb-3 mt-3 mt-sm-0"> 
                    <%=  select_tag :date_type,options_for_select([[t('search.event_date_label'), 'event_start_date'], [t('search.post_date_label'), 'post_start_date'], [t('search.application_deadline'), 'application_deadline'], [t('search.date_label'), 'created_at']], selected: params[:date_type]),  class: 'form-control shadow-none errors' %>  
                </div> 
                <div class="col-12 col-md-4 col-lg-4 pb-3">
                    <div class="date-wrapper datepicker">
                        <%= form.text_field :startDate, "data-input": "", id: "start_date",  class: "form-control shadow-none errors", placeholder: t('search.start_date'), value: (params[:startDate])%>
                        <a class="icon" title="toggle" data-toggle>
                        <i class="far fa-calendar-alt"></i>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-md-4 col-lg-4 pb-3">
                    <div class="date-wrapper datepicker">
                        <%= form.text_field :endDate,  "data-input": "", id: "end_date", class: "form-control shadow-none errors", placeholder: t('search.end_date'), value: (params[:endDate])%>
                        <a class="icon" title="toggle" data-toggle>
                            <i class="far fa-calendar-alt"></i>
                        </a>
                    </div>
                </div>  
                <div class="col-12 col-md-4 col-lg-4  mb-2 pb-3"> 
                    <%= select_tag :category, options_for_select(event_category_options, :selected => params[:category]), {:multiple => true, :class => "form-control shadow-none errors",:id => "event_category",data: {:placeholder => t('search.event_category')} } %>
                </div> 
                <div class="col-12 col-md-4 col-lg-4 px-3">
                        <%= form.text_field :keyword, id: "end_date", class: "form-control shadow-none errors", value: (params[:keyword]), placeholder: t('search.keyword_search') %>
                </div>
                <div class="col-12 col-md-4 col-lg-2 my-3 my-md-0">
                    <%= form.submit t( 'btn.student_search'), :class => 'admin-search-btn py-1 w-100 com-bg-color text-white', :id => 'search' %>
                </div>
            </div>      
        </div>
    
        <div class="search-result company-dashboard col-12 px-3 pb-5 mb-5">
            <div class="row p-2 shadow bg-white info-box">
            <div class="col-8 col-xl-10 mb-3">
                <h1><%= t('search.search_title') %></h1>
            </div>
            <div class="col-11 col-md-4 col-xl-2 mb-3 pt-2 border com-border-color com-font-color text-center mx-3 mx-md-0 shadow-sm">
                <h3><%= t('search.total_count') %> <%=   @results_event.total_count %> <%= t('search.event_count') %> </h3>
            </div>
                <% if @results_event.present? %>
                    <div class="d-none d-md-block w-100">   
                        <table class="table table-bordered table-responsive-md">
                            <thead class="com-bg-color text-white">
                                <tr>
                                    <th class="w-12" scope="col"><%= Company::Company.human_attribute_name('company_name') %></th>
                                    <th class="w-12" scope="col"><%= Company::Event.human_attribute_name('event_name') %></th>
                                    <th class="w-20" scope="col"> <%= t('event.title.event_category') %></th>
                                    <th class="w-20" scope="col"><%= t('event.title.event_date') %></th>
                                    <th class="w-12" scope="col"><%= Company::Event.human_attribute_name('venue') %></th>
                                    <th class="w-12" scope="col"><%= t('search.date_label') %></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @results_event.each_with_index do |event,index| %>
                                <tr data-link="<%= admin_company_manage_event_details_path(:eventid => event.id) %>">
                                    <td class="text-break"><%= event.company_name %></td>
                                    <td class="text-break"><%= event.event_name %></td>
                                    <td class="text-break">
                                    <% unless event.category.nil? %>
                                            <% event.category.each do |v| %>
                                                <% if v != nil %>
                                                    <%= t("event.category.#{Company::Event.event_categories.key(v)}") %>
                                                    <% if event.category.length > 1 && event.category.last != v %>
                                                        <%= ',' %>
                                                    <% end %>
                                                <% end %>
                                            <% end %>
                                        <% end %>
                                    </td>
                                    <td class="text-break"><%= l event.event_start_date %>～<%= l event.event_end_date %></td>
                                    <td class="text-break"><%= event.venue %></td>
                                    <td><%= l(event.created_at.strftime('%Y-%m-%d').to_date, default: '-')%></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-12 my-2 px-4 d-content d-md-none">
                        <% @results_event.each_with_index do |event,index| %>
                            <div class="mobile-table row std-info-box p-3 my-4 rounded" data-link="<%= admin_company_manage_event_details_path(:eventid => event.id) %>">                                                   
                                <span class="h6 com-font-color col-4"><%= Company::Company.human_attribute_name('company_name') %></span>
                                <span class="col-8 text-muted text-break"><%= event.company_name %></span><br>
                                <span class="h6 com-font-color col-4"><%= Company::Event.human_attribute_name('event_name') %></span>
                                <span class="col-8 text-muted text-break"><%= event.event_name %></span><br>
                                <span class="h6 com-font-color col-4"><%= t('event.title.event_category') %></span>
                                <span class="col-8 text-muted text-break">
                                    <% unless event.category.nil? %>
                                        <% event.category.each do |v| %>
                                            <% if v != nil %>
                                                <%= t("event.category.#{Company::Event.event_categories.key(v)}") %>
                                                    <% if event.category.length > 1 && event.category.last != v %>
                                                        <%= ',' %>
                                                    <% end %>
                                                <% end %>
                                            <% end %>
                                    <% end %>
                                </span><br>
                                <span class="h6 com-font-color col-4"><%= t('event.title.event_date') %></span>
                                <span class="col-8 text-muted text-break"><%= l event.event_start_date %>～<%= l event.event_end_date %></span><br>
                                <span class="h6 com-font-color col-4"><%= Company::Event.human_attribute_name('venue') %></span>
                                <span class="col-8 text-muted text-break"><%= event.venue %></span><br>
                                <span class="h6 com-font-color col-4"><%= t('search.date_label') %></span>
                                <span class="col-8 text-muted text-break"><%= l(event.created_at.strftime('%Y-%m-%d').to_date, default: '-')%></span><br>
                            </div>
                        <% end %>                          
                    </div>
                    <div class="col-12 d-flex justify-content-center mt-2 mx-2">
                        <%= paginate @results_event %>
                    </div>
                <% else %>
                <div class="h3 col-12 mb-3">
                        <%= t('search.no_result') %>
                    </div>
                <% end %> 
            </div>
        </div>
    </div>    
<% end %>
<%= javascript_pack_tag "admin/admin_search.js" %>
<%= javascript_pack_tag 'common.js'%>
<%= javascript_pack_tag "student/event_search.js" %>