config/routes.rb
Rails.application.routes.draw do
  namespace :communication do
    resources :communications, only: [:index,:new ,:create]
    resources :communication_details, only: [:new,:create]
     #conversation row click
     get "conversation_forum/:id", to: "communications#conversation_forum", as: "conversation_forum" 
  end
  get 'rails/g'
  get 'rails/controller'
  #For admin sing_in
  get 'bl-admin', as: "bl-admin", to:"admin/dashboard#admin"
   
   # commons Controller
   scope ':scop_name' do
    get "user_setting" ,to: "commons#user_setting"
    get "genuine_password" ,to: "commons#genuine_password"
   end
   patch "genuine_password_change/:confirmation_token" ,to: "commons#genuine_password_change" ,as: 'genuine_password_change'
   patch "user_setting_update" ,to: "commons#user_setting_update"
   get "get_region_name_by_prefecturename/:name", to: "commons#get_region_name_by_prefecturename"

  namespace :welcome do
    get 'welcomes/index', as: 'index'
    get 'student', as: 'student', to: "welcomes#student_index"
    get 'company', as: 'company', to: "welcomes#company_index"
    get 'contact', as: "contact", to:"welcomes#contact_index"
    get 'privacy', as: "privacy", to:"welcomes#privacy_index"
    get 'term_condition', as: "term_condition", to:"welcomes#term_condition_index"
    get 'registration_complete', as: "registration_complete", to:"welcomes#registration_complete"
    post 'contact_create', as: "contact_create", to:"welcomes#contact_create"
    get 'student_login', as: "student_login", to:"welcomes#student_login"
    get 'student_register', as: "student_register", to:"welcomes#student_register"
    get 'company_login', as: "company_login", to:"welcomes#company_login"
    get 'company_register', as: "company_register", to:"welcomes#company_register"
  end

  namespace :company do
    resources :companies, only: [:index,:edit,:update, :create,:show]
    resources :vacancies , only: [:index,:new,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    resources :events
    #Student Search and Detail
    get "students_search" , to: "search#student_search"
    get "student_details/:id", to: "search#student_details", as: "student_details"
    get "index", to: "search#index"
    get "favourite_student/:id", to: "search#favourite_student", as: "favourite_student" 
    get "getLocationDetails", to: "search#getLocationDetails"
    get "favourite_student_index", to: "companies#favourite_student_index"
    get "join_event_student_list/:id", to: "companies#join_event_student_list", as: "join_event_student_list"
    #set mail setting
    get "mail_settings/:mail_setting", to: "companies#mail_settings"
  end

  namespace :student do
    resources :students, only: [:index,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    get "student_smart_brain_diagnosis" , to: "assessments#student_smart_brain_diagnosis"
    get "student_potential_desire_type_diagnosis" , to: "assessments#student_potential_desire_type_diagnosis"
    get "student_behavioral_trait_type" , to: "assessments#student_behavioral_trait_type"
    #company Search and Detail
    get "companies_search" , to: "search#company_search"
    get "companies_detail/:id" , to: "search#company_detail"
    get "favourite_company/:id", to: "search#favourite_company"
    #Seach Vacancy and Detail
    get "vacancy_search" , to: "search#vacancy_search"
    get "favourite_vacancy/:id", to: "search#favourite_vacancy"
    #Search Event
    get "search_event", to: "search#search_event"
    get "search_event_detail/:id" , to: "search#search_event_detail", as: "event_details"
    get "favourite_event/:id", to: "search#favourite_event"
    get "join_event/:id", to: "search#join_event"

    get "prefecture_name/:id", to: "students#prefecture_name"
    get "favourite_company_index", to: "students#favourite_company_index"
    get "favourite_vacancy_index", to: "students#favourite_vacancy_index"
    get "favourite_event_index", to: "students#favourite_event_index"
    get "join_event_index", to: "students#join_event_index" 
  end

  devise_for :users, path: "users", controllers: { sessions: "users/sessions",passwords: "users/passwords", registrations: "users/registrations", confirmations: 'users/confirmations' }
  devise_scope :user do
    get "/logout", to: "users/sessions#destroy", as: :logout
    get "users", to: "welcome/welcomes#index"
  end

  devise_for :admins, path: "admins", controllers: { sessions: "admin/admins/sessions",passwords: "admin/admins/passwords"}
  devise_scope :admins do
    get "sign_in", to: "admin/admins/sessions#new"
    get "logout", to: "admin/admins/sessions#destroy"
  end

  namespace :admin do
    get 'dashboard/index'
    get 'password_change' , to: "commons#admin_password_change"
    post 'password_update' , to: "commons#password_update"
    get 'admin_student_setting', to: "student_manage/student#admin_student_setting"
    get 'admin_company_setting', to: "company_manage/company#admin_company_setting"
    get 'set_permission/:type_id/:user_id', to: "commons#set_permission"
    resources :backup_db

    namespace :student_manage do
      # Admin Student
      get 'student_search', to: 'student#student_search'
      get 'student_details', to: 'student#student_details'
      get 'student_edit', to: 'student#student_edit'
      get 'student_delete', to: 'student#student_delete'
      post 'student_update/:id', to: 'student#student_update'
      get 'admin_favourite_student', to: 'student#admin_favourite_student' 
    end
    namespace :company_manage do
      # Admin Company
      get 'company_search', to: 'company#company_search'
      get 'company_details', to: 'company#company_details'
      get 'company_edit', to: 'company#company_edit'
      post 'company_update/:id', to: 'company#company_update', as: "company_update"
      get 'company_delete', to: 'company#company_delete'
      get 'favourite_company', to: 'company#favourite_company'

      # Admin Event 
      get 'event_search', to: 'events#event_search'
      get 'event_details', to: 'events#event_details'
      get 'event_edit', to: 'events#event_edit'
      post 'event_update/:id', to: 'events#event_update', as: "event_update"
      get 'event_delete', to: 'events#event_delete'

      # Admin Vacancy
      get 'vacancy_search', to: 'vacancies#vacancy_search'
      get 'vacancy_details', to: 'vacancies#vacancy_details'
      get 'vacancy_edit', to: 'vacancies#vacancy_edit'
      post 'vacancy_update/:id', to: 'vacancies#vacancy_update', as: "vacancy_update"
      get 'vacancy_delete', to: 'vacancies#vacancy_delete'
    end
  end
 
  root to: 'welcome/welcomes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/backup_db.rb
class Admin::BackupDb < ApplicationRecord
    self.table_name = "backup_dbs"
    validates :name, length: { maximum: 255 }, presence: true
    validates :backup_schedule, length: { maximum: 255 }, presence: true,uniqueness: true
    validates :destroy_schedule, length: { maximum: 255 }, presence: true,uniqueness: true
    validates :file_type, length: { maximum: 255 }, presence: true

    #enum for backup_shedule options
    enum backup_shedule: { a_day: 1, weekely: 2, monthly: 3}
    #enum for destroy_shedule options
    enum destroy_shedule: { week: 1, month: 2, three_monthly: 3}
end

app/controllers/admin/backup_db_controller.rb
class Admin::BackupDbController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin_backup_db, only: %i[ new show edit update destroy ]
  include Admin::BackupDbHelper
  layout 'layouts/template/admin'
  require "sidekiq/api"

  # GET /admin/backup_dbs or /admin/backup_dbs.json
  def index
    @admin_backup_dbs = Admin::BackupDb.all
    @admin_backup_db = Admin::BackupDb.new
  end

  # GET /admin/backup_dbs/1 or /admin/backup_dbs/1.json
  def show
    search_query = search_backup_details
    @backup_db_details = Admin::BackupDetail.search_backupdetail(search_query)
    @backup_db_details = Kaminari.paginate_array(@backup_db_details).page(params[:page]).per(12) 
    puts params[:from_to_date]
  end

  # GET /admin/backup_dbs/new
  def new
    @admin_backup_db = Admin::BackupDb.new
  end

  # GET /admin/backup_dbs/1/edit
  def edit
    @admin_backup_db = Admin::BackupDb.find(params[:id])
    @admin_backup_dbs = Admin::BackupDb.all
    render :index
  end

  # POST /admin/backup_dbs or /admin/backup_dbs.json
  def create
    @admin_backup_db = Admin::BackupDb.new(admin_backup_db_params)
    @admin_backup_dbs = Admin::BackupDb.all
    de_date = get_delete_date(@admin_backup_db.destroy_schedule,Date.today)
    
      respond_to do |format|
        if @admin_backup_db.save
          # backup_job = BackupDbJob.set(:wait => 10.minutes).perform_later(10.minutes, @admin_backup_db.file_type,@admin_backup_db.id)
          #JOBS Running
          backup_job = BackupDbJob.set(:wait_until =>get_backup_scheduletime(@admin_backup_db.backup_schedule)).perform_later(get_backup_scheduletime(@admin_backup_db.backup_schedule), @admin_backup_db.file_type,@admin_backup_db.id)

          destory_job = DeleteBackupJob.set(:wait_until =>get_destory_scheduletime(@admin_backup_db.destroy_schedule)).perform_later(@admin_backup_db.id)
          
          @admin_backup_db.update_columns(delete_date: de_date,backup_job_id: backup_job.provider_job_id, delete_job_id: destory_job.provider_job_id )


          @admin_backup_db = Admin::BackupDb.new
          format.html { render :index, notice: "Backup db was successfully created." }
          format.json { render :index, status: :created, location: @admin_backup_db }
        else
          format.html { render :index, status: :unprocessable_entity }
          format.json { render json: @admin_backup_db.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /admin/backup_dbs/1 or /admin/backup_dbs/1.json
  def update
    respond_to do |format|
      @admin_backup_dbs = Admin::BackupDb.all
      if @admin_backup_db.update(admin_backup_db_params)
        de_date = get_delete_date(@admin_backup_db.destroy_schedule,Date.today)
        Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.backup_job_id).delete
        Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.delete_job_id).delete

        backup_job = BackupDbJob.set(:wait_until =>get_backup_scheduletime(@admin_backup_db.backup_schedule)).perform_later(get_backup_scheduletime(@admin_backup_db.backup_schedule), @admin_backup_db.file_type,@admin_backup_db.id)
        # backup_job = BackupDbJob.set(:wait => 10.minutes).perform_later(10.minutes, @admin_backup_db.file_type,@admin_backup_db.id)

        destory_job = DeleteBackupJob.set(:wait_until =>get_destory_scheduletime(@admin_backup_db.destroy_schedule)).perform_later(@admin_backup_db.id)
          
        @admin_backup_db.update_columns(delete_date: de_date,backup_job_id: backup_job.provider_job_id, delete_job_id: destory_job.provider_job_id )

        @admin_backup_db = Admin::BackupDb.new
        format.html { render :index, notice: "Backup db was successfully updated." }
        format.json { render :index, status: :ok, location: @admin_backup_db }
      else
        @admin_backup_db = Admin::BackupDb.new
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @admin_backup_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/backup_dbs/1 or /admin/backup_dbs/1.json
  def destroy
    
    Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.backup_job_id).delete unless  Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.backup_job_id).nil?
    Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.delete_job_id).delete unless Sidekiq::ScheduledSet.new.find_job(@admin_backup_db.delete_job_id).nil?
    backup_db_details = Admin::BackupDetail.where(backup_dbs_id: @admin_backup_db.id)
      if backup_db_details.present?
        backup_db_details.each do |backup| 
          if backup.file_type.attached?
            backup.file_type.purge
          end
          backup.destroy
        end
      end
    @admin_backup_db.destroy
    respond_to do |format|
      format.html { redirect_to admin_backup_db_index_path, notice: "Backup db was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_backup_db
      @admin_backup_db = Admin::BackupDb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_backup_db_params
      params.require(:admin_backup_db).permit(:name, :backup_schedule, :destroy_schedule, :remark, :file_type,:backup_job_id,:delete_job_id)
    end

    # Search Params With Query Check
    def search_backup_details
      search_from_to,search_backup_id = ''

      search_backup_id = if params[:id].blank?
        params[:id] =
          ''
      else
        "backup_details.backup_dbs_id = #{params[:id]}"
      end

      search_from_to = if params[:from_to_date].blank?
        params[:from_to_date] =
          ''
      else
        two_date = date_range_split_from_flatpickr(params[:from_to_date])
        "backup_details.created_at between '#{two_date[0]} 00:00' and '#{two_date[1]} 23:59'"
      end
      [search_from_to,search_backup_id]
    end
end

app/helpers/admin/backup_db_helper.rb
module Admin::BackupDbHelper
  #Database backup shedule options
  def backup_options
    Admin::BackupDb.backup_shedules.map{ |k,v| [t("backup_db.backup_schedule_options.#{v}"), v] }
  end

  #Database backup shedule options
  def destroy_options
    Admin::BackupDb.destroy_shedules.map{ |k,v| [t("backup_db.destroy_schedule_options.#{v}"), v] }
  end

  #to get destory_shedule time
  def get_backup_scheduletime(bk_time)
    sch_time = Time.zone.now
    if (bk_time.to_i == 1)
        sch_time = Time.zone.today.end_of_day
    elsif (bk_time.to_i == 2)
      sch_time = Time.now.end_of_week
    else
      sch_time = Time.now.end_of_month
    end
    return sch_time
  end

  #to get backup_shedule time
  def get_destory_scheduletime(bk_time)
    sch_time = Time.zone.now
    if (bk_time.to_i == 1)
        sch_time = sch_time.end_of_week
    elsif (bk_time.to_i == 2)
      sch_time = sch_time.end_of_month
    else
      sch_time = (sch_time + 2.months).end_of_month
    end
    return sch_time
  end

  #get to run delete schedule time for next
  def get_delete_date(destory_mode,delete_date)
    sch_time = delete_date
    current_date = Date.today
    if (destory_mode.to_i == 1)
        sch_time = (current_date.at_beginning_of_week.to_s) == (sch_time.at_beginning_of_week.to_s) ?  sch_time.at_beginning_of_week :  sch_time.next_week
    elsif (destory_mode.to_i == 2)
      sch_time = (current_date.at_beginning_of_month.to_s) == (sch_time.at_beginning_of_month.to_s) ? sch_time.at_beginning_of_month : sch_time.next_month
    else
      sch_time = (current_date - 2.months).at_beginning_of_month
    end
    return sch_time
  end

  #get date range for search
  def date_range_split_from_flatpickr(_date_params)
    if _date_params.include? ' to '
      _date_params.split(' to ', 0)
    else
      [_date_params,_date_params]
    end
  end

  #change bytes to megabytes
  MEGABYTES = 1024.0 * 1024.0
  def bytes_to_megabytes (bytes)
      (bytes / MEGABYTES).round(2)
  end
end

app/views/admin/backup_db/_form.html.erb
<%= form_with(model: admin_backup_db) do |form| %>
  <% if admin_backup_db.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_backup_db.errors.count, "error") %> prohibited this admin_backup_db from being saved:</h2>

      <ul>
        <% admin_backup_db.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/backup_db/edit.html.erb
<h1>Editing Admin Backup Db</h1>

<%#= render 'form', admin_backup_db: @admin_backup_db %>

<%#= link_to 'Show', @admin_backup_db %> |
<%#= link_to 'Back', admin_backup_dbs_path %>

app/views/admin/backup_db/index.html.erb
<div class="px-sm-4" id="backup-dashborad">
  <% if @admin_backup_db.id.nil? %>
    <%= form_with(model: @admin_backup_db, url: admin_backup_db_index_path) do |form|%>
      <div class="col-12 mt-3 mb-4 mb-lg-5 company-registration">
        <div class="row d-lg-flex justify-content-start shadow bg-white py-md-3 px-2 px-lg-4">
          <div class="col-12 col-md-7 col-xl-10 mb-3">
            <h1><%= t('backup_db.first_title') %></h1>
          </div>
          <div class="col-md-6 col-lg-3 px-3">
            <div class="d-flex">
              <label class="form-label"><%= Admin::BackupDb.human_attribute_name('name') %> </label>
              <label class="ml-auto required-label"><%= t('common.require') %> </label>
            </div>
            <%= form.text_field :name, class: "form-control shadow-none errors", placeholder: t('search.keyword_search')%>
            <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:name)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0">
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('file_type') %>   </label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div> 
              <%= form.select(:file_type, [['backup','.backup'], ['sql', '.sql'],['dump','.dump']],{:include_blank => ( t'select.not_select')} , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:file_type)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0"> 
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('backup_schedule') %> </label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div>
              <%= form.select(:backup_schedule, backup_options,{:include_blank => ( t'select.not_select') } , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:backup_schedule)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0">
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('destroy_schedule') %></label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div> 
              <%= form.select(:destroy_schedule, destroy_options,{:include_blank => ( t'select.not_select') } , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:destroy_schedule)[0] %></p>
          </div>

          <div class="col-12 px-3 my-3">
            <div class="d-flex">
              <label class="form-label"><%= Admin::BackupDb.human_attribute_name('remark') %>   </label>
            </div>
            <%= form.text_area :remark, class: "form-control shadow-none errors", placeholder: t('search.keyword_search')%>
          </div>

          <div class="col-md-6 col-lg-2 my-3 my-md-0">
              <%= form.submit t('btn.student_search'), :class => 'admin-search-btn w-100 admin-sidebar-color text-white py-1', :id => 'search' %>
          </div>
        </div>      
      </div>
    <% end %>
  <% else %>
    <%= form_with(model: @admin_backup_db) do |form|%> 
      <div class="col-12 mt-3 mb-4 mb-lg-5 company-registration">
        <div class="row d-lg-flex justify-content-start shadow bg-white py-md-3 px-2 px-lg-4">
          <div class="col-12 col-md-7 col-xl-10 mb-3">
            <h1><%= t('backup_db.first_title') %></h1>
          </div>
          <div class="col-md-6 col-lg-3 px-3">
            <div class="d-flex">
            <%= form.hidden_field :backup_job_id,value: @admin_backup_db.backup_job_id%>
            <%= form.hidden_field :delete_job_id,value: @admin_backup_db.delete_job_id%>
              <label class="form-label"><%= Admin::BackupDb.human_attribute_name('name') %> </label>
              <label class="ml-auto required-label"><%= t('common.require') %> </label>
            </div>
            <%= form.text_field :name, class: "form-control shadow-none errors", placeholder: t('search.keyword_search')%>
            <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:name)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0">
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('file_type') %>   </label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div> 
              <%= form.select(:file_type, [['backup','.backup'], ['sql', '.sql'],['dump','.dump']],{:include_blank => ( t'select.not_select')} , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:file_type)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0"> 
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('backup_schedule') %> </label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div>
              <%= form.select(:backup_schedule, backup_options,{:include_blank => ( t'select.not_select') } , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:backup_schedule)[0] %></p>
          </div>

          <div class="col-12 col-md-6 col-lg-3 mb-2 mt-4 mt-sm-0">
              <div class="d-flex">
                <label class="form-label"><%= Admin::BackupDb.human_attribute_name('destroy_schedule') %>  </label>
                <label class="ml-auto required-label"><%= t('common.require') %> </label>
              </div> 
              <%= form.select(:destroy_schedule, destroy_options,{:include_blank => ( t'select.not_select') } , {:class => "form-control shadow-none errors"}) %>
              <p class="ms-invalid-feedback mt-1"><%= @admin_backup_db.errors.full_messages_for(:destroy_schedule)[0] %></p>
          </div>

          <div class="col-12 px-3 my-3">
            <div class="d-flex">
              <label class="form-label"><%= Admin::BackupDb.human_attribute_name('remark') %>   </label>
            </div>
            <%= form.text_area :remark, class: "form-control shadow-none errors", placeholder: t('search.keyword_search')%>
          </div>

          <div class="col-md-6 col-lg-2 my-3 my-md-0">
              <%= form.submit t('btn.student_search'), :class => 'admin-search-btn w-100 admin-sidebar-color text-white py-1', :id => 'search' %>
          </div>
        </div>      
      </div>
    <% end %>  
  <% end %>  

  <%# Lists start %>
  <div class="search-result company-dashboard col-12  pb-5 mb-5">
    <div class="row p-2 shadow bg-white info-box">
      <div class="col-12 col-md-7 col-xl-10 mb-3">
          <h1><%= t('backup_db.title') %></h1>
      </div>
      <% if @admin_backup_dbs.present?  %>
          <div class="d-none d-md-block w-100">
              <table class="table table-bordered table-responsive-md table-responsive-lg-none">
                  <thead class="admin-sidebar-color text-white">
                      <tr>
                          <th scope="col"><%= t('backup_db.table_no') %></th>
                          <th scope="col"><%= Admin::BackupDb.human_attribute_name('name') %>  </th>
                          <th scope="col"><%= Admin::BackupDb.human_attribute_name('backup_schedule') %>  </th>
                          <th scope="col"><%= Admin::BackupDb.human_attribute_name('destroy_schedule') %></th>
                          <th scope="col"><%= Admin::BackupDb.human_attribute_name('file_type') %></th>
                          <th scope="col"><%= Admin::BackupDb.human_attribute_name('remark') %></th>
                          <th scope="col"></th>
                           <th scope="col"></th>
                      </tr>
                  </thead>
                  <tbody>
                      <% @admin_backup_dbs.each_with_index do |backup_data,index| %>
                          <tr>
                            <td class="text-break"><%= index + 1 %></td>
                            <td class="text-break"><%= backup_data.name %></td>
                            <td class="text-break"><%= t("backup_db.backup_schedule_options.#{backup_data.backup_schedule}")  %></td>
                            <td class="text-break"><%= t("backup_db.destroy_schedule_options.#{backup_data.destroy_schedule}") %></td>
                            <td class="text-break"><%= backup_data.file_type%></td>
                            <td class="text-break"><%= backup_data.remark%></td>
                            <td class="text-break">
                              <%= link_to ('<i class="fas fa-edit"></i>').html_safe,  edit_admin_backup_db_path(backup_data.id),
                              :class => 'icon-color'%>
                              <%= link_to ('<i class="fas fa-list"></i>').html_safe, admin_backup_db_path(backup_data.id),:class => 'icon-color' %>
                            </td>
                            <td class="text-break">
                                <%= link_to 'Destroy', backup_data, method: :delete, data: { confirm: 'Are you sure?' } %>
                              </td>
                          </tr>

                      <% end %>
                  </tbody>
              </table>  
          </div>
          <div class="col-12 my-2 px-4 d-content d-md-none">
              <% @admin_backup_dbs.each_with_index do |backup_data,index| %>
                  <div class="mobile-table row com-info-box p-3 my-4 rounded">
                    <span class="h6 com-font-color col-4"><%= t('backup_db.table_no') %></span>
                    <span class="col-8 text-muted text-break"><%= index+1 %></span><br>
                    <span class="h6 com-font-color col-4"><%= Admin::BackupDb.human_attribute_name('name') %></span>
                    <span class="col-8 text-muted text-break"><%= backup_data.name %></span><br>
                    <span class="h6 com-font-color col-4"><%= Admin::BackupDb.human_attribute_name('file_type') %></span>
                    <span class="col-8 text-muted text-break"><%= backup_data.file_type %></span><br>
                    <span class="h6 com-font-color col-4"><%= Admin::BackupDb.human_attribute_name('backup_schedule') %></span>
                    <span class="col-8 text-muted text-break">
                    <%= t("backup_db.backup_schedule_options.#{backup_data.backup_schedule}") %></span><br>
                    <span class="h6 com-font-color col-4"><%= Admin::BackupDb.human_attribute_name('destroy_schedule') %></span>
                    <span class="col-8 text-muted text-break">
                    <%= t("backup_db.destroy_schedule_options.#{backup_data.destroy_schedule}")%></span><br>

                    <span class="h6 com-font-color col-4"><%= Admin::BackupDb.human_attribute_name('remark') %></span>
                    <span class="col-8 text-muted text-break"><%= backup_data.remark %></span><br>
                    <span class="h6 com-font-color col-4">
                    </span>
                    <span class="col-8 text-muted text-break">
                      <%= link_to ('<i class="fas fa-edit"></i>').html_safe,  edit_admin_backup_db_path(backup_data.id) %>
                      <%= link_to ('<i class="fas fa-list"></i>').html_safe, admin_backup_db_path(backup_data.id) %>
                    </span>
                    <br>
                    <%= link_to 'Destroy', backup_data, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
              <% end %>                          
          </div>
      <% else %>
          <div class="col-12 m-2">
              <h3><%= t('search.no_result') %></h3>
          </div>
      <% end %>
    </div>
  </div>    
  <%# Lists end     %>
 
</div> 
<%= javascript_pack_tag "common.js" %>
<%= javascript_pack_tag "admin/backup.js" %>

app/views/admin/backup_db/new.html.erb
<h1>New Admin Backup Db</h1>

<%= render 'form', admin_backup_db: @admin_backup_db %>

<%= link_to 'Back', admin_backup_dbs_path %>