config/routes.rb
Rails.application.routes.draw do
  namespace :communication do
    resources :communications, only: [:index,:new ,:create]
    resources :communication_details, only: [:new,:create]
     #conversation row click
     get "conversation_forum/:id", to: "communications#conversation_forum", as: "conversation_forum" 
  end
  get 'rails/g'
  get 'rails/controller'
  #For admin sing_in
  get 'bl-admin', as: "bl-admin", to:"admin/dashboard#admin"
   
   # commons Controller
   scope ':scop_name' do
    get "user_setting" ,to: "commons#user_setting"
    get "genuine_password" ,to: "commons#genuine_password"
   end
   patch "genuine_password_change/:confirmation_token" ,to: "commons#genuine_password_change" ,as: 'genuine_password_change'
   patch "user_setting_update" ,to: "commons#user_setting_update"
   get "get_region_name_by_prefecturename/:name", to: "commons#get_region_name_by_prefecturename"

  namespace :welcome do
    get 'welcomes/index', as: 'index'
    get 'student', as: 'student', to: "welcomes#student_index"
    get 'company', as: 'company', to: "welcomes#company_index"
    get 'contact', as: "contact", to:"welcomes#contact_index"
    get 'privacy', as: "privacy", to:"welcomes#privacy_index"
    get 'term_condition', as: "term_condition", to:"welcomes#term_condition_index"
    get 'registration_complete', as: "registration_complete", to:"welcomes#registration_complete"
    post 'contact_create', as: "contact_create", to:"welcomes#contact_create"
    get 'student_login', as: "student_login", to:"welcomes#student_login"
    get 'student_register', as: "student_register", to:"welcomes#student_register"
    get 'company_login', as: "company_login", to:"welcomes#company_login"
    get 'company_register', as: "company_register", to:"welcomes#company_register"
  end

  namespace :company do
    resources :companies, only: [:index,:edit,:update, :create,:show]
    resources :vacancies , only: [:index,:new,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    resources :events
    #Student Search and Detail
    get "students_search" , to: "search#student_search"
    get "student_details/:id", to: "search#student_details", as: "student_details"
    get "index", to: "search#index"
    get "favourite_student/:id", to: "search#favourite_student", as: "favourite_student" 
    get "getLocationDetails", to: "search#getLocationDetails"
    get "favourite_student_index", to: "companies#favourite_student_index"
    get "join_event_student_list/:id", to: "companies#join_event_student_list", as: "join_event_student_list"
    #set mail setting
    get "mail_settings/:mail_setting", to: "companies#mail_settings"
  end

  namespace :student do
    resources :students, only: [:index,:edit,:update,:create,:show]
    resources :assessments, only: [:index,:update,:create]
    get "student_smart_brain_diagnosis" , to: "assessments#student_smart_brain_diagnosis"
    get "student_potential_desire_type_diagnosis" , to: "assessments#student_potential_desire_type_diagnosis"
    get "student_behavioral_trait_type" , to: "assessments#student_behavioral_trait_type"
    #company Search and Detail
    get "companies_search" , to: "search#company_search"
    get "companies_detail/:id" , to: "search#company_detail"
    get "favourite_company/:id", to: "search#favourite_company"
    #Seach Vacancy and Detail
    get "vacancy_search" , to: "search#vacancy_search"
    get "favourite_vacancy/:id", to: "search#favourite_vacancy"
    #Search Event
    get "search_event", to: "search#search_event"
    get "search_event_detail/:id" , to: "search#search_event_detail", as: "event_details"
    get "favourite_event/:id", to: "search#favourite_event"
    get "join_event/:id", to: "search#join_event"

    get "prefecture_name/:id", to: "students#prefecture_name"
    get "favourite_company_index", to: "students#favourite_company_index"
    get "favourite_vacancy_index", to: "students#favourite_vacancy_index"
    get "favourite_event_index", to: "students#favourite_event_index"
    get "join_event_index", to: "students#join_event_index" 
  end

  devise_for :users, path: "users", controllers: { sessions: "users/sessions",passwords: "users/passwords", registrations: "users/registrations", confirmations: 'users/confirmations' }
  devise_scope :user do
    get "/logout", to: "users/sessions#destroy", as: :logout
    get "users", to: "welcome/welcomes#index"
  end

  devise_for :admins, path: "admins", controllers: { sessions: "admin/admins/sessions",passwords: "admin/admins/passwords"}
  devise_scope :admins do
    get "sign_in", to: "admin/admins/sessions#new"
    get "logout", to: "admin/admins/sessions#destroy"
  end

  namespace :admin do
    get 'dashboard/index'
    get 'password_change' , to: "commons#admin_password_change"
    post 'password_update' , to: "commons#password_update"
    get 'admin_student_setting', to: "student_manage/student#admin_student_setting"
    get 'admin_company_setting', to: "company_manage/company#admin_company_setting"
    get 'set_permission/:type_id/:user_id', to: "commons#set_permission"
    resources :backup_db

    namespace :student_manage do
      # Admin Student
      get 'student_search', to: 'student#student_search'
      get 'student_details', to: 'student#student_details'
      get 'student_edit', to: 'student#student_edit'
      get 'student_delete', to: 'student#student_delete'
      post 'student_update/:id', to: 'student#student_update'
      get 'admin_favourite_student', to: 'student#admin_favourite_student' 
    end
    namespace :company_manage do
      # Admin Company
      get 'company_search', to: 'company#company_search'
      get 'company_details', to: 'company#company_details'
      get 'company_edit', to: 'company#company_edit'
      post 'company_update/:id', to: 'company#company_update', as: "company_update"
      get 'company_delete', to: 'company#company_delete'
      get 'favourite_company', to: 'company#favourite_company'

      # Admin Event 
      get 'event_search', to: 'events#event_search'
      get 'event_details', to: 'events#event_details'
      get 'event_edit', to: 'events#event_edit'
      post 'event_update/:id', to: 'events#event_update', as: "event_update"
      get 'event_delete', to: 'events#event_delete'

      # Admin Vacancy
      get 'vacancy_search', to: 'vacancies#vacancy_search'
      get 'vacancy_details', to: 'vacancies#vacancy_details'
      get 'vacancy_edit', to: 'vacancies#vacancy_edit'
      post 'vacancy_update/:id', to: 'vacancies#vacancy_update', as: "vacancy_update"
      get 'vacancy_delete', to: 'vacancies#vacancy_delete'
    end
  end
 
  root to: 'welcome/welcomes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/helpers/admin/student_manage/student_helper.rb
module Admin::StudentManage::StudentHelper
    def student_school_activity(outside_school_activity)
        admin_school_activity = Array.new
        check_val =outside_school_activity.reject { |i| i.zero? }
        check_val.each_with_index do |v,i|
        admin_school_activity << t("student.outside_activity.#{Student::Student.outside_activities.key(i+1)}")
      end
      admin_school_activity.join (", ")
    end

    # Qualification Category Type for excel Download
    def get_qualification_category_type(qualification_category_id)
        category_name = Array.new
        category_id = qualification_category_id.select { |i|  i != nil }
        category_id.each do |data|
            category_name << @qualification_category_type[data]
        end
        category_name.join(', ')
    end

  # Qualification Type for excel Download
    def get_qualification_type(qualification_type_id)
        qualification_name = Array.new
        qualification_id = qualification_type_id.select { |i|  i != nil }
        qualification_id.each do |data|
          qualification_name << @qualification_type[data]
        end
        qualification_name.join(', ')
    end

  # Industry Type for excel Download
    def get_industry_type(desire_industry_type_id)
      industy_name = Array.new
      industry_id = desire_industry_type_id.select { |i|  i != nil }
      industry_id.each do |data|
        industy_name << @desire_industry_type[data]
      end
      industy_name.join(', ')
    end

# Occupation Type for excel Download
  def get_desire_job_type(desire_job_type_id)
      job_name = Array.new
      job_id = desire_job_type_id.select { |i|  i != nil }
      job_id.each do |data|
          job_name << @desire_job_type[data]
      end
      job_name.join(', ')
  end

# Region Type for excel Download
  def get_region_type(m_region_id)
      region_name = Array.new
      region_name << @region_type[m_region_id]
      region_name.join(', ')
  end

# Prefecture Type for excel Download
  def get_prefecture_type(m_prefecture_id)
      prefecture_name = Array.new
      qual = m_prefecture_id.select { |i|  i != nil }
      qual.each do |data|
          prefecture_name << @prefecture_type[data]
      end
      prefecture_name.join(', ')
  end

  def admin_gender_type_options
    Student::Student.genders.keys.map{ |k| [t("student.gender.#{k}"), k] }
  end

end

app/helpers/student/assessments_helper.rb
module Student::AssessmentsHelper
    #call enum function for priority language
    def priority_language_options
        Student::Assessment.priority_languages.each.map{ |k,v| [t("student_assessment.priority_language.#{k}"), v] }
    end

    #call enum function for eng qualification
    def english_qualification_options
        Student::Assessment.english_qualifications.keys.map{ |k| [t("student_assessment.english_qualification.#{k}"), k] }
    end

    #call enum function for toefl_test
    def toefl_test_options
        Student::Assessment.toefl_tests.keys.map{ |k| [t("student_assessment.toefl_test.#{k}"), k] }
    end

    #call enum function for toeic_test
    def toeic_test_options
        Student::Assessment.toeic_tests.keys.map{ |k| [t("student_assessment.toeic_test.#{k}"), k] }
    end

    #for radar chart one
    def selfEevaluationChart_rank(student_assessment) 
        selfEevaluation_A , selfEevaluation_B , selfEevaluation_C , selfEevaluation_D = 0
        replaceArray = [0, 0, 0, 0]
    
          if student_assessment.nil? 
            @chartOne  = [0,0,0,0]
                  
          elsif  student_assessment.logical_and_rational.nil? or student_assessment.solid_and_planned.nil?
            @chartOne  = [0,0,0,0]    
    
          else        
            selfEevaluation_A  = sumValue(student_assessment.logical_and_rational) 
            selfEevaluation_B =  sumValue(student_assessment.solid_and_planned) 
            selfEevaluation_C =  sumValue(student_assessment.sensory_and_friendly)     
            selfEevaluation_D =  sumValue(student_assessment.adventurous_and_original)
            totalSum =  selfEevaluation_A + selfEevaluation_B + selfEevaluation_C + selfEevaluation_D
            selfEevaluation_A = calEachSum(totalSum.to_f,selfEevaluation_A.to_f)
            selfEevaluation_B = calEachSum(totalSum.to_f,selfEevaluation_B.to_f)
            selfEevaluation_C = calEachSum(totalSum.to_f,selfEevaluation_C.to_f)
            selfEevaluation_D = calEachSum(totalSum.to_f,selfEevaluation_D.to_f)
            @chartOne  = [selfEevaluation_A,selfEevaluation_B,selfEevaluation_C,selfEevaluation_D]
          end
          result = @chartOne.zip(replaceArray).map{ |x,y| x || y }
          rankArray = result.map{|value| result.select{|item| item > value }.size + 1 }
          rankedMap = {A: rankArray[0], B: rankArray[1] , C: rankArray[2], D: rankArray[3]}
          @rankedChartOne = rankedMap.sort_by {|k, v| v}    
    end

    #for radar chart two
    def potentialDesireType(student_assessment)
      love_and_desire_to_belong,desire_for_power_and_value,desire_for_freedom,desire_for_fun,desire_for_survival = 0
      @chartTwo = []
        if student_assessment.nil?
          @chartTwo = [0,0,0,0,0]
  
        elsif student_assessment.love_and_desire_to_belong.nil?  or student_assessment.desire_for_power_and_value.nil?
          @chartTwo = [0,0,0,0,0] 
  
        else  
        love_and_desire_to_belong = sumValue(student_assessment.love_and_desire_to_belong)
        desire_for_power_and_value = sumValue(student_assessment.desire_for_power_and_value) 
        desire_for_freedom = sumValue(student_assessment.desire_for_freedom)
        desire_for_fun = sumValue(student_assessment.desire_for_fun)
        desire_for_survival = sumValue(student_assessment.desire_for_survival)
        @chartTwo = [love_and_desire_to_belong,desire_for_power_and_value,desire_for_freedom,desire_for_fun,desire_for_survival]
        end
        rankArray = @chartTwo.map{|value| @chartTwo.select{|item| item > value }.size + 1 }
        rankedMap = {A: rankArray[0], B: rankArray[1] , C: rankArray[2], D: rankArray[3], E: rankArray[4]}
        @rankedChartTwo = rankedMap.sort_by {|k, v| v}
    end

    def behavioralTraitTypeChart_rank(student_assessment)
      self_expression , self_assertion , self_flexibility = 0
      if student_assessment.nil? 
        @chartThree = ["null","null","null"]
              
      elsif  student_assessment.self_expression.nil? or student_assessment.self_assertion.nil?
        @chartThree = ["null","null","null"]    
  
      else        
        self_expression = calBehavioralType(student_assessment.self_expression)
        self_assertion = calBehavioralType(student_assessment.self_assertion)
        self_flexibility = calBehavioralType(student_assessment.self_flexibility)
        @chartThree = [self_expression,self_assertion,self_flexibility]
      end
    end

    def sumValue(arrVal) 
      sum = arrVal.inject(0){|sum,x| sum + x } 
      sum
    end
  
    def calEachSum(totalSum,val) 
      dev = sprintf("%3.2f", (val/totalSum)*2).to_f
      total = (dev*100).to_i 
      total
    end

    def calBehavioralType (arrVal)

      countAtimes = 0
      countBtimes = 0

      # make the hash default to 0 so that += will work correctly
      b = Hash.new(0)

      # iterate over the array, counting duplicate entries
      arrVal.each do |v|
        b[v] += 1
      end

      b.each do |k, v|
        if k == 1
          countAtimes = v 
        else
          countBtimes = v
        end
      end
      total = countBtimes - countAtimes
      total
    end
end

app/helpers/student/students_helper.rb
module Student::StudentsHelper

    def school_type_options
        Student::Student.school_types.keys.map{ |k| [t("student.school_type.#{k}"), k] }
    end

    def subject_system_options
        Student::Student.subject_systems.keys.map{ |k| [t("student.subject_system.#{k}"), k] }
    end

    def is_beelab_activity_participate_options
        Student::Student.is_beelab_activity_participates.keys.map{ |k| [t("student.is_beelab_activity_participate.#{k}"), k] }
    end

    def gender_options
        Student::Student.genders.map { |k,v| [k, t("student.gender.#{k}")] }
    end
end

app/views/student/students/list/favourite_company_index.html.erb
<section class="student-detail container-fluid h-50  d-flex flex-column align-items-center mt-2 pt-2">
    <div class="col-11 bg-white py-5 mt-4 shadow std-info-box mb-5">
        <div class="h3"> <%= t ('common.favourite_company') %><br><hr class="title-hr"></div> 
        <div class="d-none d-md-block d-sm-none">                  
            <table class="table table-bordered table-responsive-md">
                <thead class="std-bg-color text-white">
                    <tr>
                        <th><%= Company::Company.human_attribute_name('company_name') %></th>
                        <th><%= Company::Company.human_attribute_name('m_industry_id') %></th>
                        <th><%= Company::Company.human_attribute_name('sales_amount') %></th>
                        <th><%= Company::Company.human_attribute_name('capital_amount') %></th>
                        <th><%= Company::Company.human_attribute_name('employee_count') %></th>
                        <th><%= Company::Company.human_attribute_name('company_established') %></th>
                        <th><%= Company::Company.human_attribute_name('display_address') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @all_favourite_company_list.each do |all_favourite_company| %>
                        <tr data-link="<%= student_path(:id => all_favourite_company.id) %>">
                            <td class="text-break"><%= all_favourite_company.company_name %></td>
                            <td><%= all_favourite_company.industry_name %></td>
                            <td><%= all_favourite_company.sales_amount%></td>
                            <td><%= all_favourite_company.capital_amount %></td>
                            <td><%= all_favourite_company.employee_count %></td>
                            <td><%= all_favourite_company.company_established %></td>
                            <td class="text-break"><%= all_favourite_company.display_address %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-12 my-2 d-content d-md-none d-lg-none d-xl-none">
            <% @all_favourite_company_list.each do |all_favourite_company| %>
                <div class="mobile-table row std-info-box shadow p-3 mb-4" data-link="<%= student_path(:id => all_favourite_company.id) %>">                                                   
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('company_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.company_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('m_industry_id') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.industry_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('sales_amount') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.sales_amount %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('capital_amount') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.capital_amount %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('employee_count') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.employee_count %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('company_established') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.company_established %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('display_address') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_company.display_address %></span><br>                       
                </div>
            <% end %>                          
        </div>
        <div class="col-12 d-flex justify-content-center p-4">
            <%= paginate @all_favourite_company_list %>
        </div>
    </div>
</section>
<%= javascript_pack_tag 'common.js'%>

app/views/student/students/list/favourite_event_index.html.erb
<section class="student-detail container-fluid h-50  d-flex flex-column align-items-center mt-2 pt-2">
    <div class="col-11 bg-white py-5 mt-4 shadow std-info-box mb-5">
        <div class="h3"> <%= t ('common.favourite_event') %><br><hr class="title-hr"></div> 
        <div class="d-none d-md-block d-sm-none">                  
            <table class="table table-bordered table-responsive-md">
                <thead class="std-bg-color text-white">
                    <tr>
                        <th><%= t('event.title.event_com_name') %></th>
                        <th><%= t('event.title.event_date') %></th>
                        <th><%= Company::Event.human_attribute_name('event_name') %></th>
                        <th><%= Company::Event.human_attribute_name('venue') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @all_favourite_event_list.each do |all_favourite_event| %>
                        <tr>
                            <td class="text-break" data-link="<%= student_event_details_path(:id => all_favourite_event.id) %>"><%= all_favourite_event.company_name %></td>
                            <td class="text-break"><%= all_favourite_event.event_start_date %>～<%= all_favourite_event.event_end_date %></td>
                            <td class="text-break"><%= all_favourite_event.event_name %></td>
                            <td class="text-break"><%= all_favourite_event.venue %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-12 my-2 d-content d-md-none d-lg-none d-xl-none">
            <% @all_favourite_event_list.each do |all_favourite_event| %>
                <div class="mobile-table row std-info-box p-2 my-4" data-link="<%= student_event_details_path(:id => all_favourite_event.id) %>">                                                   
                    <span class="h6 std-font-color col-4"><%= t('event.title.event_com_name')  %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_event.company_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= t('event.title.event_date') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_event.event_start_date %>～<%= all_favourite_event.event_end_date %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Event.human_attribute_name('event_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_event.event_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Event.human_attribute_name('venue') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_event.venue %></span><br>
                </div>
            <% end %>                           
        </div>
        <div class="col-12 d-flex justify-content-center p-4">
            <%= paginate @all_favourite_event_list %>
        </div>
    </div>
</section>
<%= javascript_pack_tag 'common.js'%>

app/views/student/students/list/favourite_vacancy_index.html.erb
<section class="student-detail container-fluid h-50  d-flex flex-column align-items-center mt-2 pt-2">
    <div class="col-11 bg-white py-5 mt-4 shadow std-info-box mb-5">
        <div class="h3"> <%= t ('common.favourite_vacancy') %><br><hr class="title-hr"></div> 
        <div class="d-none d-md-block d-sm-none">                  
            <table class="table table-bordered table-responsive-md">
                <thead class="std-bg-color text-white">
                    <tr>
                        <th><%= t('title.occupation_name') %></th>
                        <th><%= t('title.industry_name') %></th>
                        <th><%= Company::Company.human_attribute_name('company_name') %></th>
                        <th><%= t('title.target_city') %></th>
                        <th><%= Company::Vacancy.human_attribute_name('required_applicants')%></th>
                        <th><%= Company::Vacancy.human_attribute_name('basic_salary') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @all_favourite_vacancy_list.each_with_index do |all_favourite_vacancy| %>
                        <tr data-link="<%= company_vacancy_path(:id => all_favourite_vacancy.id) %>">
                            <td><%= all_favourite_vacancy.occupation_name %></td>
                            <td><%= all_favourite_vacancy.industry_name %></td>
                            <td><%= all_favourite_vacancy.company_name %></td>
                            <td><%= all_favourite_vacancy.postalcode_city %></td>
                            <td><%= all_favourite_vacancy.required_applicants %><%= t('unit.persons')%></td>
                            <td><%= all_favourite_vacancy.basic_salary %><%= t "unit.money" %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-12 my-2 d-content d-md-none d-lg-none d-xl-none">
            <% @all_favourite_vacancy_list.each_with_index do |all_favourite_vacancy| %>
                <div class="mobile-table row std-info-box shadow p-2 m-3" data-link="<%= company_vacancy_path(:id => all_favourite_vacancy.id) %>">                                                   
                    <span class="h6 std-font-color col-4"><%= t('title.occupation_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.occupation_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= t('title.industry_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.industry_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Company.human_attribute_name('company_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.company_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= t('title.target_city') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.postalcode_city %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Vacancy.human_attribute_name('required_applicants')%></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.required_applicants %><%= t('unit.persons')%></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Vacancy.human_attribute_name('basic_salary') %></span>
                    <span class="col-8 text-muted text-break"><%= all_favourite_vacancy.basic_salary %><%= t "unit.money" %></span><br>                       
                </div>
            <% end %>                           
        </div>
        <div class="col-12 d-flex justify-content-center p-4">
            <%= paginate @all_favourite_vacancy_list %>
        </div>
    </div>
</section>
<%= javascript_pack_tag 'common.js'%>

app/views/student/students/list/join_event_index.html.erb
<section class="student-detail container-fluid h-50  d-flex flex-column align-items-center mt-2 pt-2">
    <div class="col-11 bg-white py-5 mt-4 shadow std-info-box mb-5">
        <div class="h3"> <%= t ('common.join_event') %><br><hr class="title-hr"></div> 
        <div class="d-none d-md-block d-sm-none event-list">                  
            <table class="table table-bordered table-responsive-md">
                <thead class="std-bg-color text-white">
                    <tr>
                        <th><%= t('event.title.event_com_name') %></th>
                        <th><%= t('event.title.event_date') %></th>
                        <th><%= Company::Event.human_attribute_name('event_name') %></th>
                        <th><%= Company::Event.human_attribute_name('venue') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @all_join_event_list.each do |all_join_event| %>
                        <tr>
                            <td class="text-break e-col std" data-link="<%= company_event_path(:id => all_join_event.id) %>"><%= all_join_event.company_name %></td>
                            <td class="text-break"><%= all_join_event.event_start_date %>～<%= all_join_event.event_end_date %></td>
                            <td class="text-break"><%= all_join_event.event_name %></td>
                            <td class="text-break"><%= all_join_event.venue %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-12 my-2 d-content d-md-none d-lg-none d-xl-none">
            <% @all_join_event_list.each do |all_join_event| %>
                <div class="mobile-table row std-info-box p-2 my-4" data-link="<%= company_event_path(:id => all_join_event.id) %>">                                                   
                    <span class="h6 std-font-color col-4"><%= t('event.title.event_com_name')  %></span>
                    <span class="col-8 text-muted text-break"><%= all_join_event.company_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= t('event.title.event_date') %></span>
                    <span class="col-8 text-muted text-break"><%= all_join_event.event_start_date %>～<%= all_join_event.event_end_date %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Event.human_attribute_name('event_name') %></span>
                    <span class="col-8 text-muted text-break"><%= all_join_event.event_name %></span><br>
                    <span class="h6 std-font-color col-4"><%= Company::Event.human_attribute_name('venue') %></span>
                    <span class="col-8 text-muted text-break"><%= all_join_event.venue %></span><br>
                </div>
            <% end %>                           
        </div>
        <div class="col-12 d-flex justify-content-center p-4">
            <%= paginate @all_join_event_list %>
        </div>
    </div>
</section>
<%= javascript_pack_tag 'common.js'%>